language: python

python:
  - 3.7

dist: trusty

notifications:
  email: false

install:
  - python setup.py install
  - pip install -r requirements.txt
  - pip install .

script:
  - python -m pytest
