language: python

python:
  - 3.6

dist: trusty

notifications:
  email: false

before_install:
  # Temporal fix for networking problem: https://github.com/travis-ci/travis-ci/issues/1484
  - echo "127.0.1.1 "`hostname` | sudo tee /etc/hosts

  # export path
  - export PATH=$HOME/miniconda2/bin/:$PATH

install:
  - python setup.py install
  - pip install -r requirements.txt
  - pip install .

script:
  - python -m pytest

after_success:
    - coveralls
