sudo: required

services:
  - docker

language: python

python:
  - 3.6

dist: trusty

notifications:
  email: false

install:
  - python setup.py install
  - pip install -r requirements.txt
  - pip install .

script:
  - python -m pytest

after_success:
  - sh .travis/deploy.sh
  - test "$TRAVIS_BRANCH" = "master" && sh .travis/delopy_heroku.sh
